export interface CarData {
  id: number;
  title: string;
  image: string;
  price: string;
  type: string;
  shape: string;
  gearbox: string;
  passengers: string;
  fuel: string;
  features: string[];
  description: string;
}

export interface FirstPageData {
  title: string;
  image: string;
  text: string[];
}

export const carData: CarData[] = [
  {
    id: 0,
    title: "VW UP",
    image: "/rent-a-car-beograd-volkwagen-up.jpg",
    price: "od 17 do 25e / dan",
    type: "Mali gradski automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "4",
    fuel: "Benzin",
    features: [
      "Ekonomična potrošnja goriva",
      "Idealan za gradsku vožnju",
      "Lako parkiranje",
      "Klima uređaj",
      "Radio CD MP3",
      "ABS",
      "Airbag",
    ],
    description:
      "VW UP je kompaktan i ekonomičan gradski automobil, savršen za navigaciju kroz gužve i uske ulice. Nudi iznenađujuće prostran enterijer za svoju veličinu i odličnu potrošnju goriva.",
  },
  {
    id: 1,
    title: "Fiat Panda",
    image: "/rent-a-car-beograd-fiat-panda.jpg",
    price: "od 17 do 25e / dan",
    type: "Mali gradski automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "4",
    fuel: "Benzin",
    features: [
      "Kompaktne dimenzije",
      "Odlična preglednost",
      "Udobna vožnja",
      "Klima uređaj",
      "AUX priključak",
      "ABS",
      "Airbag",
    ],
    description:
      "Fiat Panda je mali i okretan gradski automobil, idealan za manevrisanje u uskim ulicama.  Njegova kompaktna veličina olakšava parkiranje, a udobna vožnja čini ga prijatnim za svakodnevnu upotrebu.",
  },
  {
    id: 2,
    title: "Škoda Fabia",
    image: "/rent-a-car-beograd-skoda-fabia-2.jpg",
    price: "od 20 do 28e / dan",
    type: "Mali porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: [
      "Prostran enterijer",
      "Veliki prtljažnik",
      "Ekonomična potrošnja",
      "Klima uređaj",
      "Bluetooth konekcija",
      "ABS",
      "Airbag",
    ],
    description:
      "Škoda Fabia je prostran mali porodični automobil, idealan za porodice i putovanja. Nudi veliki prtljažnik za prtljag i udoban enterijer za putnike.",
  },
  {
    id: 3,
    title: "Peugeot 208 1.4hdi ili slicno",
    image: "/rent-a-car-beograd-renault-peugeot-208.jpg",
    price: "od 20 do 30e / dan",
    type: "Mali porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Peugeot 208 je pouzdan mali porodični automobil sa ekonomičnim dizel motorom.",
  },
  {
    id: 4,
    title: "Renault Clio IV ili slično",
    image: "/rent-a-car-beograd-renault-clio-IV.jpg",
    price: "od 20 do 30e / dan",
    type: "Mali porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault Clio IV je popularan mali porodični automobil poznat po svojoj pouzdanosti i ekonomičnosti.",
  },
  {
    id: 5,
    title: "Dacia Sandero new ili slicno",
    image: "/rent-a-car-beograd-nova-dacia-sandero.jpg",
    price: "od 20 do 30e / dan",
    type: "Mali porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "Dacia Sandero je ekonomičan i prostran mali porodični automobil, idealan za gradsku vožnju i putovanja.",
  },
  {
    id: 6,
    title: "Citroen C3 ili slicno",
    image: "/rent-a-car-beograd-citroen-c3-1.6hdi.jpg",
    price: "od 22 do 30e / dan",
    type: "Mali porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Citroen C3 je moderan i udoban mali porodični automobil sa ekonomičnim dizel motorom.",
  },
  {
    id: 7,
    title: "Peugeot 207 SW",
    image: "/rent-a-car-beograd-peugeot-207-sw.jpg",
    price: "od 20 do 30e / dan",
    type: "Kombi",
    shape: "Karavan",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Peugeot 207 SW je praktičan karavan, idealan za porodice i prevoz prtljaga.",
  },
  {
    id: 8,
    title: "Renault Megane III 1.5dci",
    image: "/rent-a-car-beograd-renault-megan-3.jpg",
    price: "od 25 do 35e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault Megane III je udoban porodični automobil sa ekonomičnim dizel motorom.",
  },
  {
    id: 9,
    title: "Opel Meriva ili slicno",
    image: "/rent-a-car-beograd-opel-meriva.jpg",
    price: "od 25 do 35e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Opel Meriva je praktičan porodični automobil sa prostranim enterijerom.",
  },
  {
    id: 10,
    title: "Skoda Fabia NEW 1.4tdi",
    image: "/rent-a-car-beograd-skoda-fabia-new.jpg",
    price: "od 25 do 35e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description: "Skoda Fabia NEW je moderan i ekonomičan porodični automobil.",
  },
  {
    id: 11,
    title: "VW POLO",
    image: "/rent-a-car-beograd-vw-polo.jpg",
    price: "od 25 do 35e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description: "VW Polo je pouzdan i ekonomičan porodični automobil.",
  },
  {
    id: 12,
    title: "Fiat 500L ili slično",
    image: "/rent-a-car-beograd-fiat-500-l.jpg",
    price: "od 25 do 40e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "Fiat 500L je prostran porodični automobil sa puno prostora za putnike i prtljag.",
  },
  {
    id: 13,
    title: "Renault Scenic dci automatik",
    image: "/rent-a-car-beograd-renault-scenic-automatik.jpg",
    price: "od 25 do 40e / dan",
    type: "Kombi",
    shape: "Karavan",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault Scenic je udoban karavan sa automatskim menjačem, idealan za porodična putovanja.",
  },
  {
    id: 14,
    title: "Dacia Sandero automatik",
    image: "/rent-a-car-beograd-dacia-sandero-automatik.jpg",
    price: "od 28 do 40e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "Dacia Sandero automatik je ekonomičan porodični automobil sa automatskim menjačem.",
  },
  {
    id: 15,
    title: "Opel Astra J sedan",
    image: "/rent-a-car-beograd-opel-astra-sedan.jpg",
    price: "od 30 do 45e / dan",
    type: "Porodični automobil",
    shape: "Sedan",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "Opel Astra J sedan je elegantan porodični automobil sa automatskim menjačem.",
  },
  {
    id: 16,
    title: "New Logan automatik",
    image: "/rent-a-car-beograd-reno-logan-automatik.jpg",
    price: "od 27 do 45e / dan",
    shape: "Sedan",
    type: "Porodični automobil",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "New Logan automatik je ekonomičan porodični automobil sa automatskim menjačem.",
  },
  {
    id: 17,
    title: "VW GOLF VI+ 1.6tdi ili slično",
    image: "/VW-Golf-Plus-2012-gray.jpg",
    price: "od 33 do 45e / dan",
    type: "Porodični automobil",
    shape: "Hečbek",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "VW Golf VI+ je prostran porodični automobil sa ekonomičnim dizel motorom.",
  },
  {
    id: 18,
    title: "Fiat Tipo 1.3 dizel ili slično",
    image: "/rent-a-car-beograd-fiat-tipo-1.3-dizel.jpg",
    price: "od 30 do 50e / dan",
    type: "Porodični automobil",
    shape: "Limuzina",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description: "Fiat Tipo 1.3 dizel je ekonomičan porodični automobil.",
  },
  {
    id: 19,
    title: "FIAT 500X SUV 1.6 Mjtd",
    image: "/rent-a-car-beograd-fiat-500x-suv.jpg",
    price: "od 40 do 60e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description: "FIAT 500X SUV je moderan i prostran SUV automobil.",
  },
  {
    id: 20,
    title: "Škoda Octavia",
    image: "/Skoda-Octavia-Grey-png-hd.png",
    price: "od 35 do 60e / dan",
    type: "Porodični automobil",
    shape: "Limuzina",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description: "Škoda Octavia je prostran porodični automobil.",
  },
  {
    id: 21,
    title: "VW GOLF VII SW",
    image: "/cc_2015vkw052a_01_640_a1a1.jpg",
    price: "od 35 do 60e / dan",
    type: "Kombi",
    shape: "Karavan",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "VW Golf VII SW je prostran karavan sa ekonomičnim dizel motorom.",
  },
  {
    id: 22,
    title: "Opel ASTRA K automatik sw",
    image: "/Clipped_image_20240323_083958.png",
    price: "od 35 do 60e / dan",
    type: "Kombi",
    shape: "Karavan",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Opel Astra K automatik sw je udoban karavan sa automatskim menjačem.",
  },
  {
    id: 23,
    title: "Renault Talisman",
    image: "/rent-a-car-beograd-renault-talisman.jpg",
    price: "od 40 do 70e / dan",
    type: "Porodični automobil",
    shape: "Limuzina",
    gearbox: "Manuelni",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault Talisman je elegantna limuzina sa ekonomičnim dizel motorom.",
  },
  {
    id: 24,
    title: "VOLVO XC60 AUTOMATIK 4x4",
    image: "/a5e64564-91cd-45cc-8451-dccda080f21b.png",
    price: "od 40 do 70e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "VOLVO XC60 AUTOMATIK 4x4 je luksuzni SUV automobil sa pogonom na sva četiri točka.",
  },
  {
    id: 25,
    title: "Renault Kadjar Automatik",
    image: "/auto-magazin-srbija-2019-renault-kadjar-1.jpg",
    price: "od 40 do 70e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault Kadjar Automatik je udoban SUV automobil sa automatskim menjačem.",
  },
  {
    id: 26,
    title: "Renault ESPACE 7 Sedista",
    image: "/rentacarbeograd-7sedista-automatik.jpg",
    price: "od 50 do 80e / dan",
    type: "Kombi",
    shape: "Monovolumen",
    gearbox: "Automatik",
    passengers: "7",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Renault ESPACE 7 Sedista je prostran monovolumen sa 7 sedišta.",
  },
  {
    id: 27,
    title: "BMW 320d Automatik",
    image: "/bmw-3.20i-f30-2017-5f63b55f02df8.png",
    price: "od 50 do 90e / dan",
    type: "Luksuzni automobil",
    shape: "Limuzina",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "BMW 320d Automatik je luksuzna limuzina sa automatskim menjačem.",
  },
  {
    id: 28,
    title: "Mercedes E 200cdi NEW",
    image: "/rent-a-car-beograd-mercedes-e200-automatik.jpg",
    price: "od 50 do 100e / dan",
    type: "Luksuzni automobil",
    shape: "Limuzina",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Mercedes E 200cdi NEW je luksuzna limuzina sa automatskim menjačem.",
  },
  {
    id: 29,
    title: "Range Rover 4x4 Automatik",
    image: "/Rentacarbeograd_rangerover.png",
    price: "od 55 do 110e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "Range Rover 4x4 Automatik je luksuzni SUV automobil sa pogonom na sva četiri točka.",
  },
  {
    id: 30,
    title: "Porsche Cayenne 4x4",
    image: "/rent-a-car-beograd-porsche-cayenne-automatik-lux.jpg",
    price: "od 65 do 130e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Hibrid",
    features: ["ABS", "Airbag"],
    description:
      "Porsche Cayenne 4x4 je luksuzni SUV automobil sa hibridnim motorom.",
  },
  {
    id: 31,
    title: "BMW 530d G30 Automatik",
    image: "/Individual 1.png",
    price: "od 80 do 150e / dan",
    type: "Luksuzni automobil",
    shape: "Limuzina",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "BMW 530d G30 Automatik je luksuzna limuzina sa automatskim menjačem.",
  },
  {
    id: 32,
    title: "BMW X6 2018",
    image: "/rent-a-car-beograd-bmw-x6-automatik-4x4.jpg",
    price: "od 90 do 160e / dan",
    type: "SUV",
    shape: "SUV",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "BMW X6 2018 je luksuzni SUV automobil sa pogonom na sva četiri točka.",
  },
  {
    id: 33,
    title: "AUDI A6 50Tdi NEW",
    image: "/RentacarBeogradAudiA6Automatik.png",
    price: "od 80 do 160e / dan",
    type: "Luksuzni automobil",
    shape: "Limuzina",
    gearbox: "Automatik",
    passengers: "5",
    fuel: "Dizel",
    features: ["ABS", "Airbag"],
    description:
      "AUDI A6 50Tdi NEW je luksuzna limuzina sa automatskim menjačem.",
  },
  {
    id: 34,
    title: "Porsche Panamera 4x4",
    image: "/946636b105c3b2d514f4fcc2f0af3106.jpg",
    price: "od 100 do 200e / dan",
    type: "Luksuzni automobil",
    shape: "Limuzina",
    gearbox: "Automatik",
    passengers: "4",
    fuel: "Benzin",
    features: ["ABS", "Airbag"],
    description:
      "Porsche Panamera 4x4 je luksuzna limuzina sa pogonom na sva četiri točka.",
  },
];

export const firstPagedata: FirstPageData[] = [
  {
    title: "RENT A CAR BEOGRAD GOLD VAM PRUŽA DODATNE BESPLATNE POGODNOSTI",
    image: "/rent-a-car-beograd-fiat-500x-suv.jpg",
    text: [
      "PREUZIMANJE VOZILA NA AERODROMU",
      "ISPORUKA VOZILA NA VAŠOJ ADRESI",
      "BEZ DEPOZITA",
      "ZELENI KARTON",
      "NAVIGACIJA",
      "ZIMSKE GUME I LANCI",
    ],
  },
  {
    title: "BEOGRAD RENT A CAR AERODROM",
    image: "/rent-a-car-beograd-renault-talisman.jpg",
    text: [
      "Rent a Car Beograd - GoldRent je vaš pouzdan partner za iznajmljivanje vozila u Beogradu. Sa dugogodišnjim iskustvom u auto industriji, posvećeni smo pružanju vrhunske usluge našim klijentima.",
      "Naša moderna flota vozila i profesionalno osoblje garantuju vam bezbrižno putovanje i maksimalnu udobnost. Dostupni smo 24/7 kako bismo odgovorili na sve vaše potrebe.",
    ],
  },
  {
    title: "NAJVEĆI IZBOR AUTOMOBILA U SRBIJI PO NAJPOVOLJNIJIM CENAMA",
    image: "/rent-a-car-beograd-vw-polo.jpg",
    text: [
      "DOSTUPNI NON-STOP",
      "BEZ DODATNIH TROSKOVA",
      "RENT A CAR VOZILO NA VASIOJ ADRESI",
      "ISPORUKA NA AERODROMU",
      "BEZ OGRANICENJA NA PREDJENU KILOMETRAZU U SRBIJI!",
      "GPS I DECJE SEDISTE BESPLATNO",
    ],
  },
  {
    title: "Rent a car Beograd bez depozita - GoldRent",
    image: "/auto-magazin-srbija-2019-renault-kadjar-1.jpg",
    text: [
      "Gold Rent Rentacar Beograd u svojoj ponudi ima veliki izbor novih vozila za iznajmljivanje za svaku priliku,bez obzira na dužinu i vrstu putovanja koje obavljate.",
      "Sva naša vozila su spremna u svakom trenutku za letnju ili zimsku vožnju, auta su redovno servisirana,održavana i potpuno spremna za vožnju.",
      "Rentacar vozila u nažoj agenciji su sva KASKO osigurana i možemo da Vam ponudimo i neograničenu kilometražu uz najbolju moguću cenu,kao i dodatnu opremu..",
    ],
  },
  {
    title: "Zašto iznajmiti auto od Renta car Beograd Gold?",
    image: "/rent-a-car-beograd-fiat-tipo-1.3-dizel.jpg",
    text: [
      "GoldRent agencija za iznajmljivanje vozila u Beogradu veliki broj automobila iz svoje flote mođe da Vam ponudi bez depozita i plaćanja dodatnih usliga.Najjeftiniji rent a car je isto jedna od opcija koje mođemo Vam ponudimo.",
      "IZNAJMITE AUTOMOBIL NAJJEFTINIJI DO LUX KLASE.",
    ],
  },
  {
    title: "Luksuzna Vozila Rent a car Beograd GoldRent",
    image: "/946636b105c3b2d514f4fcc2f0af3106.jpg",
    text: [
      "Posebno smo ponosni na kategoriju luksuznih vozila. Ljubitelji offroad avantura mogu izabrati između robusnih SUV terenaca. Jeep, BMW X6, BMW X1, VW TOUAREG pleniće pažnjom na gradskim ulicama.",
      "Najnovija zvezda lux ponude je dominantni PORSCHE PANAMERA. Lux vozila i limuzine za svadbe, mature i sve svečanosti na kojima želite da se pojavite sa stilom su Audi A6, BMW X6, BMW F10, BMW 5, MERCEDES E KLASA, MERCEDES S KLASA. Iznajmljujemo luksuzne automobile sa i bez vozača.",
    ],
  },
];
